language: java
before_install:
  - chmod +x gradlew
deploy:
  provider: releases
  api_key:
    secure: AAAAB3NzaC1yc2EAAAADAQABAAACAQDWlGmKALNbOeggXeLIHoV0lwurs2NK09u+QYi9+TNyfR1OctVhxertgJ5ZIZnF56AIHeyw3tEofYgEnuk9Lt/0+J47oC37vA2JpQrDo8afWD/EN9XdT5VZfZlwP4Bg8SQNhp1ZgEpLspszxx9S8VMZoerH0NSr2fIcE5tIXIPI3q2d5An/JzplzIHLpJz/jE+w8rynxM1GX08X8o1qco14drma83X8lFAR3yGyIF8kpUbwXDSvQtw3sz7eCSyzYk1QlgcEVECd+24hm2mdzqs30qwF/3Wn7hP8IPWvnVVEuEhkY4i7ahZjHNnWKygJDgXyOiXx7MGK0vyIBx9veYSbTDVVYumZSD3P5gP6QX9L5NoPzgmJK1C7lskP97Fptu8VE5p/r1G7CZR6vlkGU0DXKEc2ExLqJAuFlThR1wEXcJl71nx5GZNJjWz4jlaikp5PU+0XKQvNnfTK2qAOvva/U3clFl9ZG/bey6Bp3UtovprR9jxaefqvztOURQ9yxGnLeU+6J9LCtjBYPKFpqNsnbQPDA1EFZpeRCljPmLQ/BRFJXH0v4XEhsfwsQV5WBkuvHLTPpgAhSjX9MiE5Mypgig9PfXYwXHaB/OQ30CAkH5NGCK8O4FVgy8Po3HjZ66M+IfOGHn1/d3eCtN1BSPOV0MfhV2tCGE0TywKF4IUzGQ==
  file: build/libs/xlr-newrelic-plugin-1.0.0.jar
  skip_cleanup: true
  on:
    tags: true
    repo: xebialabs-community/xlr-newrelic-plugin
